# Generated by Django 2.2 on 2021-01-17 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published', models.DateField(default=datetime.datetime(2021, 1, 17, 17, 46, 34, 38409), verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
