# Generated by Django 2.2 on 2021-01-17 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210117_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2021, 1, 17, 17, 49, 49, 7856), verbose_name='date published'),
        ),
    ]
