# Generated by Django 2.2 on 2021-01-19 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20210117_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 10, 27, 9, 204961), verbose_name='date published'),
        ),
    ]
